services:
  http:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - port-scanner-lab

  ssh:
    image: panubo/sshd:latest
    environment:
      SSH_USERS: "scanner:lab-password:1000"
    ports:
      - "22:22"
    networks:
      - port-scanner-lab

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: lab-password
    ports:
      - "5432:5432"
    networks:
      - port-scanner-lab

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - port-scanner-lab

networks:
  port-scanner-lab:
    name: port-scanner-lab